[package]
name = "metricsdb"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
float-ord = "0.3"
rand = "0.8"

libc = "0.2"

serde = { version = "1.0", features=["serde_derive"] }
serde_json = "1.0"

